(function (root) {
  'use strict';
  const KEY = 'lifeQuestData.v1';
  const STAT = { health:['体力','var(--red)'], intellect:['知力','var(--blue)'], creativity:['創造力','var(--purple)'], life:['生活力','var(--green)'], work:['仕事力','var(--orange)'] };
  const defaults = [
    ['gym','ジム','🏋️',20,'health',1],['study','勉強','📚',10,'intellect',1],['create','DTM / 創作','🎧',20,'creativity',1],
    ['clean','掃除','🧹',10,'life',1],['early','早起き','🌅',10,'life',1],['read','読書','📖',10,'intellect',1],
    ['workgood','仕事で良かったこと','💼',15,'work',1],['eatout','外食','🍽️',5,'life',1],['other','その他','✨',5,'life',1]
  ].map(([id,name,icon,exp,stat,amount])=>({id,name,icon,exp,stat,amount,builtin:true}));
  const achievementDefs = [
    ['first','はじめの一歩','初めて行動を記録する','✦'],['gym10','駆け出しトレーニー','ジムを10回記録する','⚔'],
    ['streak7','継続は力なり','7日連続で行動を記録する','🔥'],['hundred','冒険者','合計100回行動を記録する','♜'],
    ['creator20','創作者','創作系行動を20回記録する','♫']
  ];
  const fresh = ()=>({exp:0,stats:{health:0,intellect:0,creativity:0,life:0,work:0},logs:[],actions:defaults,achievements:[]});
  const expForLevel = level => 100 + (level-1)*25;
  function levelInfo(total){let level=1,remaining=total;while(remaining>=expForLevel(level)){remaining-=expForLevel(level);level++;}return{level,current:remaining,needed:expForLevel(level)};}
  function titleFor(level){return level>=30?'日常の勇者':level>=20?'継続する者':level>=10?'習慣の使い手':level>=5?'駆け出し冒険者':'旅立ちの新人';}
  const localDay = date => { const d=new Date(date); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
  function streak(logs){const days=[...new Set(logs.map(x=>localDay(x.at)))].sort().reverse();let n=0,d=new Date();for(const day of days){const expected=localDay(d);if(day===expected){n++;d.setDate(d.getDate()-1);}else if(n===0){d.setDate(d.getDate()-1);if(day===localDay(d)){n++;d.setDate(d.getDate()-1);}else break;}else break;}return n;}
  function unlocked(data){return achievementDefs.filter(([id])=> id==='first'?data.logs.length>=1:id==='gym10'?data.logs.filter(x=>x.actionId==='gym').length>=10:id==='streak7'?streak(data.logs)>=7:id==='hundred'?data.logs.length>=100:data.logs.filter(x=>x.stat==='creativity').length>=20).map(x=>x[0]);}
  function record(data, action, at=new Date().toISOString()){const next=JSON.parse(JSON.stringify(data));next.exp+=action.exp;next.stats[action.stat]=(next.stats[action.stat]||0)+action.amount;next.logs.unshift({id:`l${Date.now()}${Math.random()}`,actionId:action.id,name:action.name,icon:action.icon,exp:action.exp,stat:action.stat,amount:action.amount,at});const before=new Set(next.achievements);next.achievements=[...new Set([...next.achievements,...unlocked(next)])];return{data:next,newAchievements:next.achievements.filter(x=>!before.has(x))};}
  const api={fresh,expForLevel,levelInfo,titleFor,record,unlocked,streak,localDay};
  if(typeof module!=='undefined'&&module.exports) module.exports=api;
  if(typeof document==='undefined') return;
  let data=load(), tab='home';
  const app=document.querySelector('#app');
  function load(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved)return{...fresh(),...saved,stats:{...fresh().stats,...saved.stats}};}catch(e){}return fresh();}
  function save(){localStorage.setItem(KEY,JSON.stringify(data));}
  const e=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const pageHead=(k,t)=>`<div class="eyebrow">${k}</div><h1 class="page-title">${t}</h1>`;
  function statCard(){return `<div class="card stats">${Object.entries(STAT).map(([k,[name,color]])=>{const v=data.stats[k]||0;return `<div><div class="stat-top"><span><i class="dot" style="background:${color}"></i>${name}</span><b>${v}</b></div><div class="bar"><div class="fill" style="width:${Math.min(v%10*10,100)}%;background:${color}"></div></div></div>`}).join('')}</div>`;}
  function logList(logs){return logs.length?`<div class="card logs">${logs.map(x=>`<div class="log-row"><div class="log-main"><span>${e(x.icon)}</span><div><b>${e(x.name)}</b><br><time>${new Date(x.at).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</time></div></div><span class="log-exp">+${x.exp} EXP</span></div>`).join('')}</div>`:`<div class="card empty">まだ記録はありません。<br>小さな冒険を始めましょう。</div>`;}
  function home(){const l=levelInfo(data.exp),today=data.logs.filter(x=>localDay(x.at)===localDay(new Date())),sum=today.reduce((a,x)=>a+x.exp,0);return `${pageHead('YOUR ADVENTURE','Life Quest')}<section class="hero"><div class="level-row"><div><div class="eyebrow">CURRENT LEVEL</div><div class="level">Lv.${l.level}</div></div><div class="title">〈 ${titleFor(l.level)} 〉</div></div><div class="exp-meta"><span>EXP ${l.current} / ${l.needed}</span><span>あと ${l.needed-l.current}</span></div><div class="bar"><div class="fill gold" style="width:${l.current/l.needed*100}%"></div></div></section><div class="section-head"><h2>ステータス</h2><small>総EXP ${data.exp}</small></div>${statCard()}<div class="section-head"><h2>今日の冒険</h2><small>${today.length} actions</small></div><div class="card today-total"><span>今日の獲得EXP</span><strong>+${sum}</strong></div>${logList(today)}<button class="primary" data-open-record>＋ 行動を記録</button>`;}
  function recordPage(){return `${pageHead('ACTION LIST','行動を記録')}<p style="color:var(--muted);font-size:13px;margin:-10px 0 18px">カードをタップすると、すぐに記録されます。</p><div class="action-grid">${data.actions.map(actionCard).join('')}</div>`;}
  function actionCard(a){return `<button class="action" data-record="${e(a.id)}"><span class="arrow">＋</span><span class="icon">${e(a.icon)}</span><b>${e(a.name)}</b><small>+${a.exp} EXP · ${STAT[a.stat][0]} +${a.amount}</small></button>`;}
  function statusPage(){return `${pageHead('YOUR GROWTH','ステータス')} ${statCard()}<div class="section-head"><h2>最近の成長</h2></div>${logList(data.logs.slice(0,20))}`;}
  function achievementsPage(){return `${pageHead('TROPHY ROOM','実績')}<div>${achievementDefs.map(([id,n,d,icon])=>`<div class="card achievement ${data.achievements.includes(id)?'':'locked'}"><div class="badge">${data.achievements.includes(id)?icon:'?'}</div><div><b>${n}</b><p>${d}</p></div></div>`).join('')}</div>`;}
  function menuPage(){return `${pageHead('SETTINGS','メニュー')}<button class="menu-row" data-calendar><b>▦ 冒険カレンダー</b><p>日ごとの行動記録を振り返る</p></button><button class="menu-row" data-custom><b>⚔ 行動のカスタマイズ</b><p>行動の追加・編集・削除</p></button><button class="menu-row" data-export><b>⇩ データをエクスポート</b><p>JSONファイルとして保存</p></button><button class="menu-row" data-import><b>⇧ データをインポート</b><p>保存したデータを復元</p></button><button class="menu-row danger" data-reset><b>⟲ データをリセット</b><p>すべての冒険記録を削除</p></button>`;}
  function render(){app.innerHTML=({home,record:recordPage,status:statusPage,achievements:achievementsPage,menu:menuPage})[tab]();document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
  function doRecord(id){const a=data.actions.find(x=>x.id===id);if(!a)return;const oldLevel=levelInfo(data.exp).level,result=record(data,a);data=result.data;save();render();let extra=levelInfo(data.exp).level>oldLevel?`<strong>LEVEL UP! Lv.${levelInfo(data.exp).level}</strong>`:'';if(result.newAchievements.length) extra+=`<strong>実績解除：${achievementDefs.find(x=>x[0]===result.newAchievements[0])[1]}</strong>`;toast(`<b>${e(a.name)}を記録しました！</b><strong>+${a.exp} EXP</strong>${STAT[a.stat][0]} +${a.amount}${extra}`);closeModal();}
  function toast(html){const el=document.createElement('div');el.className='toast';el.innerHTML=html;document.querySelector('#toastRoot').append(el);setTimeout(()=>el.remove(),3100);}
  function modal(html){document.querySelector('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${html.title}</h2><button class="close" data-close>×</button></div>${html.body}</div></div>`;}
  function closeModal(){document.querySelector('#modalRoot').innerHTML='';}
  function recordModal(){modal({title:'行動を選択',body:`<div class="action-grid">${data.actions.map(actionCard).join('')}</div>`});}
  function customModal(){modal({title:'行動のカスタマイズ',body:`<div id="customList">${data.actions.map(a=>`<div class="card custom-item"><span>${e(a.icon)}　<b>${e(a.name)}</b></span><span class="custom-actions"><button data-edit="${e(a.id)}">✎</button><button data-delete="${e(a.id)}">×</button></span></div>`).join('')}</div><button class="primary" data-add>＋ 新しい行動</button>`});}
  function calendarModal(){const now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate();let cells='<span></span>'.repeat(first);for(let d=1;d<=last;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,count=data.logs.filter(x=>localDay(x.at)===key).length;cells+=`<button data-day="${key}" class="day ${key===localDay(now)?'today':''}"><b>${d}</b>${count?`<small>${count}件</small>`:''}</button>`;}modal({title:`${y}年 ${m+1}月`,body:`<div class="week"><span>日</span><span>月</span><span>火</span><span>水</span><span>木</span><span>金</span><span>土</span></div><div class="calendar">${cells}</div>`});}
  function dayModal(day){const logs=data.logs.filter(x=>localDay(x.at)===day);modal({title:day.replaceAll('-',' / '),body:logList(logs)});}
  function editModal(id){const a=data.actions.find(x=>x.id===id)||{id:'custom-'+Date.now(),name:'',icon:'✨',exp:10,stat:'life',amount:1};modal({title:id?'行動を編集':'新しい行動',body:`<form id="actionForm" data-id="${e(a.id)}"><label class="field">行動名<input name="name" required maxlength="30" value="${e(a.name)}"></label><label class="field">アイコン<input name="icon" maxlength="4" value="${e(a.icon)}"></label><label class="field">獲得EXP<input name="exp" type="number" min="1" max="999" required value="${a.exp}"></label><label class="field">成長するステータス<select name="stat">${Object.entries(STAT).map(([k,v])=>`<option value="${k}" ${k===a.stat?'selected':''}>${v[0]}</option>`).join('')}</select></label><label class="field">上昇量<input name="amount" type="number" min="1" max="99" required value="${a.amount}"></label><button class="primary" type="submit">保存する</button></form>`});}
  document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;render();scrollTo(0,0);}else if(b.dataset.record)doRecord(b.dataset.record);else if(b.hasAttribute('data-open-record'))recordModal();else if(b.hasAttribute('data-close'))closeModal();else if(b.hasAttribute('data-calendar'))calendarModal();else if(b.dataset.day)dayModal(b.dataset.day);else if(b.hasAttribute('data-custom'))customModal();else if(b.hasAttribute('data-add'))editModal();else if(b.dataset.edit)editModal(b.dataset.edit);else if(b.dataset.delete){if(confirm('この行動を削除しますか？')){data.actions=data.actions.filter(x=>x.id!==b.dataset.delete);save();customModal();}}else if(b.hasAttribute('data-reset')){if(confirm('すべてのデータをリセットしますか？')){data=fresh();save();render();}}else if(b.hasAttribute('data-export')){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='life-quest-data.json';a.click();URL.revokeObjectURL(a.href);}else if(b.hasAttribute('data-import'))document.querySelector('#importFile').click();});
  document.addEventListener('submit',ev=>{if(ev.target.id!=='actionForm')return;ev.preventDefault();const f=new FormData(ev.target),a={id:ev.target.dataset.id,name:f.get('name').trim(),icon:f.get('icon').trim()||'✨',exp:+f.get('exp'),stat:f.get('stat'),amount:+f.get('amount')};const i=data.actions.findIndex(x=>x.id===a.id);if(i>=0)data.actions[i]={...data.actions[i],...a};else data.actions.push(a);save();render();customModal();toast('<b>行動を保存しました</b>');});
  document.querySelector('#importFile').addEventListener('change',ev=>{const file=ev.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const v=JSON.parse(reader.result);if(!Array.isArray(v.actions)||!Array.isArray(v.logs))throw Error();data={...fresh(),...v,stats:{...fresh().stats,...v.stats}};save();render();toast('<b>データを復元しました</b>');}catch(e){alert('読み込めないファイルです。');}};reader.readAsText(file);ev.target.value='';});
  render();
})(typeof globalThis!=='undefined'?globalThis:this);
